import { useEffect, useState } from 'react';
import { CheckCircle2, Scale, Sparkles } from 'lucide-react';
import { api } from '../api';
import type { Interest, Trip } from '../types';

export function DecisionStudio({ trip, onTrip }: { trip: Trip; onTrip: (trip: Trip, note: string) => void }) {
  const collection = trip.preferenceCollection;
  const [scores, setScores] = useState<Record<Interest, number>>(trip.groupPreference.interestScores);
  const [saving, setSaving] = useState(false);
  useEffect(() => setScores(trip.groupPreference.interestScores), [trip.groupPreference.interestScores]);
  if (!collection) return <section className="mt-6 rounded-[28px] border border-dashed border-stone-300 bg-white p-8 text-center"><Scale className="mx-auto text-stone-300" /><h2 className="mt-3 text-xl font-bold text-ink">Decision Studio unlocks after the calls</h2><p className="mt-2 text-sm text-stone-500">Complete the Vocal Bridge preference workflow above to compare requests, compromises and projected happiness.</p></section>;
  const dirty = JSON.stringify(scores) !== JSON.stringify(trip.groupPreference.interestScores);
  const adjust = (interest: Interest, amount: number) => setScores((current) => ({ ...current, [interest]: Math.min(5, Math.max(1, Number((current[interest] + amount).toFixed(2)))) }));
  const apply = async () => { setSaving(true); try { const response = await api.approvePreferences(scores, trip); onTrip(response.trip, 'Decision approved. Flexible itinerary times, happiness, route priorities and the activity feed were updated.'); } catch (error) { onTrip(trip, error instanceof Error ? error.message : 'Could not update the trip.'); } finally { setSaving(false); } };
  return <section className="mt-6 rounded-[32px] border border-moss/20 bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-moss">Step 3 · Decision Studio</p><h2 className="mt-1 text-2xl font-bold text-ink">See the compromise, tune priorities, update the actual trip.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">The score is derived from itinerary fit—not generated randomly. Updating the trip reprioritizes flexible stops and recalculates every traveler.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${collection.status === 'approved' && !dirty ? 'bg-emerald-100 text-moss' : 'bg-amber-100 text-amber-800'}`}>{collection.status === 'approved' && !dirty ? 'Trip updated' : dirty ? 'Changes not applied' : 'Ready for admin'}</span></div>
    <div className="mt-5 grid gap-3 lg:grid-cols-3">{collection.calls.map((call) => <article key={call.travelerId} className="rounded-2xl border border-stone-200 bg-[#fafbf9] p-4"><div className="flex items-center justify-between gap-2"><b className="text-ink">{call.name}</b><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-moss">{call.happiness}% plan fit</span></div><p className="mt-3 text-xs leading-5 text-stone-600">“{call.summary}”</p><div className="mt-3 flex flex-wrap gap-1.5">{call.topPriorities.map((priority) => <span key={priority} className="rounded-full bg-white px-2 py-1 text-[10px] font-bold capitalize ring-1 ring-stone-200">{priority}</span>)}</div><p className="mt-3 text-xs leading-5 text-stone-600"><b className="text-ink">Negotiated compromise:</b> {call.compromise}</p>{call.happinessBreakdown && <div className="mt-4 grid grid-cols-2 gap-2 text-[10px] text-stone-500"><span>Interest {call.happinessBreakdown.interestMatch}%</span><span>Pace {call.happinessBreakdown.paceMatch}%</span><span>Constraints {call.happinessBreakdown.constraintMatch}%</span><span>Compromise {call.happinessBreakdown.compromiseCoverage}%</span></div>}</article>)}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-2xl bg-[#eff6f1] p-5"><div className="flex items-center justify-between"><div><b className="text-ink">Admin priority adjustment</b><p className="mt-1 text-xs text-stone-600">1 is optional; 5 is protected in the route.</p></div><span className="text-xs font-bold text-moss">Editable anytime</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(Object.keys(scores) as Interest[]).map((interest) => <div key={interest} className="flex items-center justify-between rounded-xl bg-white px-3 py-2.5"><span className="capitalize text-sm font-semibold">{interest}</span><span className="flex items-center gap-2"><button onClick={() => adjust(interest, -0.5)} className="grid h-7 w-7 place-items-center rounded-lg border border-stone-200 font-bold">−</button><b className="w-8 text-center text-sm text-moss">{scores[interest]}</b><button onClick={() => adjust(interest, 0.5)} className="grid h-7 w-7 place-items-center rounded-lg bg-moss font-bold text-white">+</button></span></div>)}</div></div><aside className="rounded-2xl bg-[#fff8e9] p-5"><p className="eyebrow text-coral">Projected plan</p><p className="mt-2 text-4xl font-bold text-ink">{trip.groupPreference.groupHappiness ?? 0}%</p><p className="mt-1 text-xs text-stone-500">Current group happiness · fairness penalty {trip.groupPreference.fairnessPenalty ?? 0}</p><p className="mt-4 text-xs leading-5 text-stone-600">Applying changes recalculates the itinerary and this score. Flights, hotels and completed activities remain protected.</p><button disabled={saving || (!dirty && collection.status === 'approved')} onClick={() => void apply()} className="mt-5 w-full rounded-xl bg-ink px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Sparkles className="mr-2 inline" size={16} />{saving ? 'Updating trip…' : collection.status === 'approved' ? 'Update trip again' : 'Approve & update trip'}</button>{collection.status === 'approved' && !dirty && <p className="mt-3 flex items-center gap-2 text-xs font-bold text-moss"><CheckCircle2 size={15} />Current priorities are applied</p>}</aside></div>
  </section>;
}
