import { Bot, Scale } from 'lucide-react';
import type { Interest, Trip } from '../types';

const interests: Interest[] = ['culture', 'history', 'food', 'photography', 'shopping', 'nightlife', 'nature'];

export function TravelerFitOverview({ trip }: { trip: Trip }) {
  const calls = new Map((trip.preferenceCollection?.calls ?? []).map((call) => [call.travelerId, call]));
  return <section className="rounded-[30px] border border-stone-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Group happiness · deterministic plan fit</p><h2 className="mt-1 text-xl font-bold text-ink">How well does this trip serve everyone?</h2><p className="mt-2 text-sm text-stone-600">65% interest match · 15% pace · 10% constraints · 10% compromise coverage.</p></div><div className="rounded-2xl bg-[#eff6f1] px-5 py-3 text-right"><p className="text-[10px] font-bold uppercase tracking-widest text-moss">Group happiness</p><p className="text-3xl font-bold text-ink">{trip.groupPreference.groupHappiness ?? '—'}{trip.groupPreference.groupHappiness !== undefined && '%'}</p><p className="text-[10px] text-stone-500">Fairness gap {trip.groupPreference.fairnessGap ?? '—'} pts</p></div></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{trip.travelers.map((traveler) => { const call = calls.get(traveler.id); const top = interests.slice().sort((left, right) => traveler.interests[right] - traveler.interests[left]).slice(0, 3); return <article key={traveler.id} className="rounded-2xl bg-[#fafbf9] p-4"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-ink text-xs font-bold text-white">{traveler.initials}</span><div><p className="font-bold text-ink">{traveler.name}</p><p className="text-xs capitalize text-stone-500">{traveler.pacePreference} pace · {traveler.foodPreference}</p></div></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${call ? 'bg-emerald-100 text-moss' : 'bg-stone-200 text-stone-500'}`}>{call ? `${call.happiness}% plan fit` : 'Call pending'}</span></div><div className="mt-4 space-y-2">{top.map((interest) => <div key={interest} className="grid grid-cols-[88px_1fr_30px] items-center gap-2 text-xs"><span className="capitalize text-stone-600">{interest}</span><span className="h-2 overflow-hidden rounded-full bg-stone-200"><span className="block h-full rounded-full bg-coral" style={{ width: `${traveler.interests[interest] * 20}%` }} /></span><b className="text-right text-ink">{traveler.interests[interest]}/5</b></div>)}</div>{call && <p className="mt-4 text-xs leading-5 text-stone-600"><b className="text-ink">Why:</b> {call.happinessExplanation}</p>}</article>; })}</div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_auto]"><div className="flex gap-3 rounded-2xl bg-[#fff8e9] p-4"><Bot className="shrink-0 text-coral" /><p className="text-sm leading-6 text-ink"><b>Negotiated route:</b> {trip.groupPreference.explanation}</p></div><div className="flex items-center gap-2 rounded-2xl bg-stone-100 px-4 py-3 text-xs text-stone-600"><Scale className="text-moss" size={17} /><span>Average {trip.groupPreference.averageHappiness ?? '—'}%<br />Penalty {trip.groupPreference.fairnessPenalty ?? '—'}</span></div></div></section>;
}
