import { Activity, Brain, Clock3, Heart, ShieldCheck, Sparkles } from 'lucide-react';
import type { Interest, Trip } from '../types';

const interestLabel: Record<Interest, string> = {
  culture: 'Culture', history: 'History', food: 'Food', photography: 'Photography',
  shopping: 'Shopping', nightlife: 'Nightlife', nature: 'Nature',
};

const behaviorNote = (reason: string) => reason.split(';')[0]?.trim().replace(/[.;]$/, '') || reason;

export function TravelDnaPanel({ trip }: { trip: Trip }) {
  const changes = trip.travelDna.changes ?? [];
  const calls = new Map((trip.preferenceCollection?.calls ?? []).map((call) => [call.travelerId, call]));

  return <div className="space-y-6">
    <section className="rounded-[28px] bg-ink px-5 py-7 text-white sm:rounded-[32px] sm:px-7 sm:py-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-emerald-200">Negotiation memory</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">What Odyssey remembers about the group.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Clear likes, dislikes, constraints, and accepted compromises are more useful than unexplained numeric ratings. These notes help the next negotiation start with context.</p></div><div className="w-fit rounded-2xl bg-white/10 px-5 py-4"><p className="text-xs font-bold uppercase tracking-widest text-white/50">Learning confidence</p><p className="mt-1 text-3xl font-bold text-emerald-200">{trip.travelDna.confidence ?? 50}%</p><p className="mt-1 text-[10px] text-white/50">Grows with verified trip behavior</p></div></div></section>

    <section><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow text-moss">Traveler profiles</p><h2 className="mt-1 text-2xl font-bold text-ink">Useful context for future negotiation</h2></div><span className="text-xs text-stone-500">Editable in Group planning</span></div><div className="mt-4 grid gap-4 md:grid-cols-2">{trip.travelers.map((traveler) => {
      const ranked = (Object.entries(traveler.interests) as [Interest, number][]).sort((left, right) => right[1] - left[1]);
      const likes = ranked.filter(([, score]) => score >= 4).slice(0, 3);
      const lowPriority = ranked.filter(([, score]) => score <= 2).reverse().slice(0, 2);
      const call = calls.get(traveler.id);
      return <article key={traveler.id} className="min-w-0 rounded-2xl border border-stone-200 bg-white p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-ink text-xs font-bold text-white">{traveler.initials}</span><div className="min-w-0"><h3 className="font-bold text-ink">{traveler.name}</h3><p className="mt-1 text-xs capitalize text-stone-500">{traveler.pacePreference} pace · {traveler.budgetPreference} budget</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-moss"><Heart size={12} />Strong likes</p><div className="mt-2 flex flex-wrap gap-1.5">{likes.length ? likes.map(([interest]) => <span key={interest} className="rounded-full bg-[#eff6f1] px-2.5 py-1 text-xs font-semibold text-moss">{interestLabel[interest]}</span>) : <span className="text-xs text-stone-400">Still learning</span>}</div></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-stone-400">Low priority / avoid</p><div className="mt-2 flex flex-wrap gap-1.5">{lowPriority.length ? lowPriority.map(([interest]) => <span key={interest} className="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-semibold text-stone-600">{interestLabel[interest]}</span>) : <span className="text-xs text-stone-400">None recorded</span>}</div></div></div><div className="mt-4 rounded-xl bg-stone-50 p-3 text-xs leading-5 text-stone-600"><b className="text-ink">Food or constraint:</b> {traveler.foodPreference}</div><div className="mt-3 rounded-xl border border-moss/15 bg-[#f6fbf7] p-3 text-xs leading-5 text-stone-600"><b className="text-moss">Negotiation memory:</b> {call?.compromise || call?.summary || 'No call summary yet. Use the stated profile until a traveler confirms a compromise.'}</div></article>;
    })}</div></section>

    <section className="grid gap-6 xl:grid-cols-[0.75fr_1.25fr]"><article className="rounded-[28px] bg-[#eff6f1] p-5 sm:p-6"><div className="flex items-center gap-2"><Brain className="text-moss" /><h2 className="text-xl font-bold text-ink">Group learning</h2></div><p className="mt-4 text-sm leading-7 text-stone-700">{behaviorNote(trip.travelDna.learning)}.</p><div className="mt-5 rounded-xl bg-white p-4 text-xs leading-5 text-stone-600"><b className="text-ink">How it is used:</b> propose better trade-offs, avoid known friction, and reprioritize flexible activities while protecting bookings and explicit non-negotiables.</div><div className="mt-3 flex items-start gap-2 rounded-xl bg-white p-4 text-xs leading-5 text-stone-600"><ShieldCheck className="mt-0.5 shrink-0 text-moss" size={16} /><span>Odyssey should ask again when confidence is low or when a new trip has different travelers, budget, or accessibility needs.</span></div></article><article className="rounded-[28px] border border-stone-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow">Evidence log</p><h2 className="mt-1 text-xl font-bold text-ink">What changed and why</h2></div><Activity className="shrink-0 text-coral" /></div>{changes.length ? <div className="mt-5 space-y-3">{changes.map((change) => <div key={change.id} className="rounded-xl bg-stone-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b className="capitalize text-sm text-ink">{change.dimension} preference updated</b><span className="inline-flex items-center gap-1 text-[10px] font-bold text-stone-400"><Clock3 size={12} />{new Date(change.createdAt).toLocaleString()}</span></div><p className="mt-2 text-xs leading-5 text-stone-600">{behaviorNote(change.reason)}.</p></div>)}</div> : <div className="mt-6 rounded-2xl border border-dashed border-stone-300 p-8 text-center"><Sparkles className="mx-auto text-stone-300" /><p className="mt-3 font-bold text-ink">No behavioral evidence yet</p><p className="mt-2 text-sm text-stone-500">Complete, skip, or spend longer at an activity in Live trip to create the first evidence-backed memory.</p></div>}</article></section>
  </div>;
}
